import { createContext, useContext, useState, type ReactNode } from "react";

type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const value: LanguageContextType = {
    language,
    setLanguage,
    t: (key: string, params?: Record<string, string | number>) => {
      let text = translations[language]?.[key] ?? translations.en?.[key] ?? key;
      if (params) {
        for (const [k, v] of Object.entries(params)) {
          text = text.replace(`{${k}}`, String(v));
        }
      }
      return text;
    },
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "DevPilot",
    "nav.dashboard": "Dashboard",
    "nav.projects": "Projects",
    "nav.chat": "Chat",
    "nav.documentation": "Documentation",
    "nav.health": "Health",
    "nav.settings": "Settings",
    "navbar.subtitle": "AI Developer Assistant",
    "settings.title": "Settings",
    "settings.language": "Language",
    "settings.language_label": "Select your preferred language",
    "settings.provider": "Provider",
    "settings.provider_label": "Choose which LLM backend to use",
    "settings.ollama_model": "Ollama Model",
    "settings.groq_model": "Groq Model",
    "settings.ollama_url": "Ollama Base URL",
    "settings.generation": "Generation",
    "settings.temperature": "Temperature",
    "settings.max_tokens": "Max Tokens",
    "settings.save": "Save Settings",
    "settings.saved": "Settings saved",
    "settings.save_error": "Failed to save settings",
    "settings.rag": "RAG",
    "settings.rag_desc": "Semantic code chunking for vector search",
    "settings.rag_chunk_lines": "Chunk Lines",
    "settings.rag_overlap": "Overlap Lines",
    "settings.rag_max_chunks": "Max Chunks per File",
    "settings.rag_max_results": "Max Search Results",
    "project.title": "Project",
    "doc.title": "Documentation",
    "dashboard.title": "Dashboard",
    "viewer.title": "File Viewer",
    "viewer.select": "Select a file to view its contents.",
    "viewer.code": "Code",
    "viewer.ai": "AI",
    "viewer.explain": "Explain with AI",
    "viewer.generating": "Generating...",
    "viewer.waiting": "Waiting for response...",
    "viewer.no_explanation": "No explanation generated yet.",
    "viewer.chars": "chars",
    "viewer.error": "Unable to generate explanation.",
    "stats.total_files": "Total Files",
    "stats.lines": "Lines",
    "stats.functions": "Functions",
    "stats.classes": "Classes",
    "stats.files_line": "{files} files, {lines} lines",
    "explorer.title": "Project Explorer",
    "explorer.search": "Search files...",
    "explorer.search_code": "Search code...",
    "explorer.empty": "Analyze a project to display its files.",
    "chat.title": "Project Chat",
    "chat.no_project": "Open a project from the Dashboard first to start asking questions.",
    "chat.asking_about": "Asking about:",
    "chat.placeholder": "Ask about your project...",
    "chat.send": "Send",
    "chat.thinking": "Thinking...",
    "chat.empty": "Ask anything about your project — architecture, dependencies, how to add features, etc.",
    "chat.error": "Error: Unable to get an answer.",
    "chat.clear": "Clear history",
    "project.select": "Select Project",
    "project.analyze": "Analyze",
    "project.analyzing": "Analyzing...",
    "project.browse": "Browse",
    "project.path_placeholder": "Select a project...",
    "project.analyze_title": "Analyze Project",
    "current_project.title": "Current Project",
    "current_project.no_project": "No project selected",
    "current_project.close": "Close Project",
    "recent.title": "Recent Projects",
    "recent.empty": "No projects analyzed yet.",
    "rag.ready": "RAG Active",
    "rag.not_ready": "RAG Unavailable",
    "rag.chunks": "{chunks} chunks indexed",
    "rag.project_chunks": "{chunks} for this project",
    "rag.rebuild": "Rebuild Index",
    "rag.clear": "Clear Index",
    "rag.chunk_lines": "Chunk size: {n} lines",
    "rag.overlap": "Overlap: {n} lines",
    "rag.reindexed": "{files} files reindexed",
    "rag.rebuild_failed": "Rebuild failed",
    "rag.clear_success": "RAG index cleared",
    "rag.clear_failed": "Clear failed",
    "recent.clear": "Clear all",
    "lang.en": "English",
    "lang.es": "Spanish",
    "settings.ai_model": "AI Model",
    "settings.ai_model_desc": "Choose which AI service to use for chat, code review, and documentation.",
    "settings.model_quality": "Model quality",
    "settings.ollama_model_name": "Ollama model name",
    "settings.ollama_model_placeholder": "qwen2.5-coder:7b",
    "settings.advanced": "Advanced settings",
    "settings.temperature_desc": "Lower = more precise. Higher = more creative.",
    "settings.temperature_precise": "0 — Precise",
    "settings.temperature_creative": "2 — Creative",
    "settings.max_tokens_desc": "Maximum response length from the AI.",
    "settings.ollama_url_desc": "Change only if Ollama runs on a different machine.",
    "settings.rag_desc_short": "How code is split and searched for AI context.",
    "settings.api_key": "{provider} API Key",
    "settings.api_key_placeholder": "sk-... ({provider} API key)",
    "settings.test": "Test",
    "settings.connected": "Connected",
    "settings.failed": "Failed",
    "settings.load_error": "Failed to load settings",
    "settings.test_connection_failed": "Connection test failed",
    "settings.switched_to_auto": "Switched to Auto provider",
    "settings.enter_api_key": "Enter an API key for {provider} first",
    "badge.local": "Local",
    "badge.free": "Free",
    "badge.key": "Key",
    "provider.ollama.label": "Ollama",
    "provider.ollama.desc": "Open-source models, runs on your machine",
    "provider.openai.label": "OpenAI",
    "provider.openai.desc": "GPT-4o, GPT-4o-mini. Fast & powerful",
    "provider.anthropic.label": "Claude",
    "provider.anthropic.desc": "Claude 3.5 Sonnet. Great for code review",
    "provider.google.label": "Gemini",
    "provider.google.desc": "Gemini 2.0 Flash. Google's latest",
    "provider.groq.label": "Groq",
    "provider.groq.desc": "Fast inference. Free tier available",
    "provider.auto.label": "Auto",
    "provider.auto.desc": "Smart detection. Ollama → Groq → first available",
    "preset.fast.label": "Fast",
    "preset.fast.desc": "Quick responses",
    "preset.balanced.label": "Balanced",
    "preset.balanced.desc": "Good quality",
    "preset.code.label": "Code",
    "preset.code.desc": "Best for code",
    "project.overview": "Project Overview",
    "project.statistics": "Statistics",
    "project.actions": "Actions",
    "project.rag_index": "RAG Index",
    "project.code_review": "Code Review",
    "project.file_explorer": "File Explorer",
    "project.file_viewer": "File Viewer",
    "project.recent_projects": "Recent Projects",
    "project_actions.summary": "AI Summary",
    "project_actions.generating_summary": "Generating Summary\u2026",
    "project_actions.explain": "Explain Project",
    "project_actions.analyzing": "Analyzing Project\u2026",
    "project_actions.project_summary": "Project Summary",
    "project_actions.project_analysis": "Project Analysis",
    "current_project.previous": "Previous project",
    "current_project.resume": "Resume",
    "current_project.opening": "Opening...",
    "current_project.copy": "Copy",
    "current_project.share": "Share",
    "current_project.export": "Export",
    "current_project.resume_error": "Failed to resume project",
    "current_project.share_error": "Failed to generate share link",
    "current_project.link_copied": "Link copied to clipboard",
    "stats.lang_distribution": "Language Distribution",
    "code_review.run": "AI Code Review",
    "code_review.running": "Running Code Review\u2026",
    "code_review.title": "Code Review",
    "code_review.analyzing": "Analyzing source files\u2026",
    "code_review.categories_reviewed": "{count} categories reviewed",
    "code_review.issues": "issues",
    "code_review.issue_single": "issue",
    "code_review.ai_fix": "AI Fix",
    "code_review.generating_fix": "Generating fix...",
    "code_review.waiting_ai": "Waiting for AI...",
    "code_review.suggested_fix": "Suggested fix",
    "code_review.copy": "Copy",
    "code_review.file": "File:",
    "code_review.line": "Line: ~{line}",
    "code_review.issue_label": "Issue:",
    "code_review.fix_label": "Fix:",
    "code_review.failed_fix": "Failed to fix: {file}",
    "code_review.copied": "Code copied to clipboard",
    "code_review.copy_failed": "Failed to copy",
    "chat.new_session": "New session",
    "chat.delete": "Delete",
    "chat.no_sessions": "No sessions yet",
    "chat.collapse": "Collapse",
    "chat.expand": "Expand",
    "chat.sources": "Sources:",
    "chat.searching": "Searching project code...",
    "chat.error_loading_session": "Error loading session",
    "chat.error_creating_session": "Error creating session",
    "chat.error_deleting_session": "Error deleting session",
    "chat.error_response": "Error getting response",
    "chat.history_cleared": "History cleared",
    "chat.error_clearing": "Error clearing history",
    "viewer.editing": "EDITING",
    "viewer.save": "Save",
    "viewer.saving": "Saving\u2026",
    "viewer.cancel": "Cancel",
    "viewer.search": "Search",
    "viewer.edit": "Edit",
    "viewer.search_placeholder": "Search in file...",
    "viewer.saved": "File saved",
    "viewer.save_error": "Error saving file",

    "docs.title": "Documentation",
    "docs.generate_doc": "Generate Documentation",
    "docs.generating_doc": "Generating Documentation\u2026",
    "docs.generate_readme": "Generate README",
    "docs.generating_readme": "Generating README\u2026",
    "docs.export_pdf": "Export PDF",
    "docs.readme_title": "README generated",
    "docs.readme_path": "Path:",
    "docs.readme_overwritten": "Overwritten existing file.",
    "docs.readme_created": "Created new file.",
    "docs.error_generating": "Error generating documentation",
    "docs.readme_success": "README generated successfully",
    "docs.readme_error": "Error generating README",
    "docs.export_first": "Generate documentation first",
    "docs.allow_popups": "Allow popups to export PDF",
    "docs.about.title": "About DevPilot",
    "docs.about.text": "DevPilot is a local-first AI developer assistant. It analyzes your source code, indexes it with vector search (RAG), and lets you chat with an LLM that understands your project. All processing happens on your machine.",
    "docs.quick_start.title": "Quick Start",
    "docs.quick_start.step1": "Open a project folder from the Projects page (drag & drop or browse).",
    "docs.quick_start.step2": "Wait for analysis to complete. The RAG index builds automatically.",
    "docs.quick_start.step3": "Go to Chat and ask questions about your code.",
    "docs.quick_start.step4": "Use the File Explorer to view, edit, and search files.",
    "docs.quick_start.step5": "Configure your LLM provider in Settings (Ollama or Groq).",
    "docs.shortcuts.title": "Keyboard Shortcuts",
    "docs.shortcuts.hint": "Press {key} anywhere to see all shortcuts.",
    "docs.shortcuts.show": "Show keyboard shortcuts",
    "docs.shortcuts.close": "Close modal / cancel",
    "docs.shortcuts.file_search": "File search (Explorer)",
    "docs.shortcuts.project_search": "Search in project code",
    "docs.shortcuts.file_find": "Search inside file (Viewer)",
    "docs.shortcuts.toggle_edit": "Toggle edit mode (Viewer)",
    "docs.shortcuts.save_file": "Save file (Viewer)",
    "docs.shortcuts.send": "Send message (Chat)",
    "docs.providers.title": "LLM Providers",
    "docs.providers.ollama_title": "Ollama (default)",
    "docs.providers.ollama_desc": "Local models via Ollama. Install Ollama separately and pull a model (e.g. {cmd}).",
    "docs.providers.groq_title": "Groq (cloud)",
    "docs.providers.groq_desc": "Fast cloud inference via Groq API. Create a free key at {url} and add it to your .env file.",
    "docs.rag.title": "RAG (Retrieval-Augmented Generation)",
    "docs.rag.para1": "DevPilot indexes your project code into ChromaDB, a local vector database. When you ask a question in Chat, it retrieves the most relevant code snippets and includes them as context for the LLM, showing source citations inline.",
    "docs.rag.para2": "The index rebuilds automatically when you open or upload a project. Saving a file auto-reindexes just that file.",
    "docs.api.title": "API Endpoints",
    "docs.api.description": "All API routes are prefixed with {prefix}. Full Swagger docs at {docs}.",
    "docs.api.health": "Basic health check",
    "docs.api.health_detailed": "Full service status",
    "docs.api.metrics": "Prometheus metrics",
    "docs.api.settings": "LLM/RAG settings",
    "docs.api.analyze": "Analyze project stats",
    "docs.api.question_stream": "Streaming project Q&A",
    "docs.api.tool_stream": "Chat with tool-calling",
    "docs.api.export": "Export project as ZIP",
    "docs.api.share": "Generate share link",
    "docs.api.shared": "View shared project",
  },
  es: {
    "app.name": "DevPilot",
    "nav.dashboard": "Dashboard",
    "nav.projects": "Proyectos",
    "nav.chat": "Chat",
    "nav.documentation": "Documentación",
    "nav.health": "Estado",
    "nav.settings": "Configuración",
    "navbar.subtitle": "Asistente de Desarrollo IA",
    "settings.title": "Configuración",
    "settings.language": "Idioma",
    "settings.language_label": "Selecciona tu idioma preferido",
    "settings.provider": "Proveedor",
    "settings.provider_label": "Elige qué backend LLM usar",
    "settings.ollama_model": "Modelo Ollama",
    "settings.groq_model": "Modelo Groq",
    "settings.ollama_url": "URL Base Ollama",
    "settings.generation": "Generación",
    "settings.temperature": "Temperatura",
    "settings.max_tokens": "Máx. Tokens",
    "settings.save": "Guardar Cambios",
    "settings.saved": "Configuración guardada",
    "settings.save_error": "Error al guardar configuración",
    "settings.rag": "RAG",
    "settings.rag_desc": "Fragmentación semántica de código para búsqueda vectorial",
    "settings.rag_chunk_lines": "Líneas por Fragmento",
    "settings.rag_overlap": "Líneas de Solapamiento",
    "settings.rag_max_chunks": "Máx. Fragmentos por Archivo",
    "settings.rag_max_results": "Máx. Resultados de Búsqueda",
    "project.title": "Proyecto",
    "doc.title": "Documentación",
    "dashboard.title": "Dashboard",
    "viewer.title": "Visor de Archivos",
    "viewer.select": "Selecciona un archivo para ver su contenido.",
    "viewer.code": "Código",
    "viewer.ai": "IA",
    "viewer.explain": "Explicar con IA",
    "viewer.generating": "Generando...",
    "viewer.waiting": "Esperando respuesta...",
    "viewer.no_explanation": "Aún no se generó ninguna explicación.",
    "viewer.chars": "caracteres",
    "viewer.error": "No se pudo generar la explicación.",
    "stats.total_files": "Archivos Totales",
    "stats.lines": "Líneas",
    "stats.functions": "Funciones",
    "stats.classes": "Clases",
    "stats.files_line": "{files} arch., {lines} líneas",
    "explorer.title": "Explorador de Archivos",
    "explorer.search": "Buscar archivos...",
    "explorer.search_code": "Buscar código...",
    "explorer.empty": "Analiza un proyecto para ver sus archivos.",
    "chat.title": "Chat del Proyecto",
    "chat.no_project": "Abre un proyecto desde el Dashboard primero para hacer preguntas.",
    "chat.asking_about": "Preguntando sobre:",
    "chat.placeholder": "Pregunta sobre tu proyecto...",
    "chat.send": "Enviar",
    "chat.thinking": "Pensando...",
    "chat.empty": "Pregunta cualquier cosa sobre tu proyecto — arquitectura, dependencias, cómo añadir funciones, etc.",
    "chat.error": "Error: No se pudo obtener una respuesta.",
    "chat.clear": "Limpiar historial",
    "project.select": "Seleccionar Proyecto",
    "project.analyze": "Analizar",
    "project.analyzing": "Analizando...",
    "project.browse": "Examinar",
    "project.path_placeholder": "Selecciona un proyecto...",
    "project.analyze_title": "Analizar Proyecto",
    "current_project.title": "Proyecto Actual",
    "current_project.no_project": "Ningún proyecto seleccionado",
    "current_project.close": "Cerrar Proyecto",
    "recent.title": "Proyectos Recientes",
    "recent.empty": "Aún no se analizaron proyectos.",
    "rag.ready": "RAG Activo",
    "rag.not_ready": "RAG No Disponible",
    "rag.chunks": "{chunks} fragmentos indexados",
    "rag.project_chunks": "{chunks} para este proyecto",
    "rag.rebuild": "Reconstruir Índice",
    "rag.clear": "Limpiar Índice",
    "rag.chunk_lines": "Tamaño: {n} líneas",
    "rag.overlap": "Solapamiento: {n} líneas",
    "rag.reindexed": "{files} archivos reindexados",
    "rag.rebuild_failed": "Error al reconstruir",
    "rag.clear_success": "Índice RAG limpiado",
    "rag.clear_failed": "Error al limpiar",
    "recent.clear": "Limpiar todo",
    "lang.en": "Inglés",
    "lang.es": "Español",
    "settings.ai_model": "Modelo de IA",
    "settings.ai_model_desc": "Elige qué servicio de IA usar para chat, revisión de código y documentación.",
    "settings.model_quality": "Calidad del modelo",
    "settings.ollama_model_name": "Nombre del modelo Ollama",
    "settings.ollama_model_placeholder": "qwen2.5-coder:7b",
    "settings.advanced": "Opciones avanzadas",
    "settings.temperature_desc": "Menor = más preciso. Mayor = más creativo.",
    "settings.temperature_precise": "0 — Preciso",
    "settings.temperature_creative": "2 — Creativo",
    "settings.max_tokens_desc": "Longitud máxima de respuesta de la IA.",
    "settings.ollama_url_desc": "Cambia solo si Ollama se ejecuta en otra máquina.",
    "settings.rag_desc_short": "Cómo se divide y busca el código para el contexto de IA.",
    "settings.api_key": "Clave API de {provider}",
    "settings.api_key_placeholder": "sk-... (clave API de {provider})",
    "settings.test": "Probar",
    "settings.connected": "Conectado",
    "settings.failed": "Falló",
    "settings.load_error": "Error al cargar configuración",
    "settings.test_connection_failed": "Error de conexión",
    "settings.switched_to_auto": "Cambiado a proveedor Auto",
    "settings.enter_api_key": "Ingresa una clave API para {provider} primero",
    "badge.local": "Local",
    "badge.free": "Gratis",
    "badge.key": "Clave",
    "provider.ollama.label": "Ollama",
    "provider.ollama.desc": "Modelos open-source, se ejecutan en tu máquina",
    "provider.openai.label": "OpenAI",
    "provider.openai.desc": "GPT-4o, GPT-4o-mini. Rápidos y potentes",
    "provider.anthropic.label": "Claude",
    "provider.anthropic.desc": "Claude 3.5 Sonnet. Ideal para revisión de código",
    "provider.google.label": "Gemini",
    "provider.google.desc": "Gemini 2.0 Flash. Lo último de Google",
    "provider.groq.label": "Groq",
    "provider.groq.desc": "Inferencia rápida. Nivel gratuito disponible",
    "provider.auto.label": "Auto",
    "provider.auto.desc": "Detección inteligente. Ollama → Groq → primero disponible",
    "preset.fast.label": "Rápido",
    "preset.fast.desc": "Respuestas rápidas",
    "preset.balanced.label": "Balanceado",
    "preset.balanced.desc": "Buena calidad",
    "preset.code.label": "Código",
    "preset.code.desc": "Ideal para código",
    "project.overview": "Resumen del Proyecto",
    "project.statistics": "Estadísticas",
    "project.actions": "Acciones",
    "project.rag_index": "Índice RAG",
    "project.code_review": "Revisión de Código",
    "project.file_explorer": "Explorador de Archivos",
    "project.file_viewer": "Visor de Archivos",
    "project.recent_projects": "Proyectos Recientes",
    "project_actions.summary": "Resumen IA",
    "project_actions.generating_summary": "Generando Resumen\u2026",
    "project_actions.explain": "Explicar Proyecto",
    "project_actions.analyzing": "Analizando Proyecto\u2026",
    "project_actions.project_summary": "Resumen del Proyecto",
    "project_actions.project_analysis": "Análisis del Proyecto",
    "current_project.previous": "Proyecto anterior",
    "current_project.resume": "Reanudar",
    "current_project.opening": "Abriendo...",
    "current_project.copy": "Copiar",
    "current_project.share": "Compartir",
    "current_project.export": "Exportar",
    "current_project.resume_error": "Error al retomar proyecto",
    "current_project.share_error": "Error al generar link de compartir",
    "current_project.link_copied": "Link copiado al portapapeles",
    "stats.lang_distribution": "Distribución de Lenguajes",
    "code_review.run": "Revisión de Código IA",
    "code_review.running": "Ejecutando Revisión\u2026",
    "code_review.title": "Revisión de Código",
    "code_review.analyzing": "Analizando archivos fuente\u2026",
    "code_review.categories_reviewed": "{count} categorías revisadas",
    "code_review.issues": "problemas",
    "code_review.issue_single": "problema",
    "code_review.ai_fix": "Corrección IA",
    "code_review.generating_fix": "Generando corrección...",
    "code_review.waiting_ai": "Esperando a la IA...",
    "code_review.suggested_fix": "Corrección sugerida",
    "code_review.copy": "Copiar",
    "code_review.file": "Archivo:",
    "code_review.line": "Línea: ~{line}",
    "code_review.issue_label": "Problema:",
    "code_review.fix_label": "Corrección:",
    "code_review.failed_fix": "Error al corregir: {file}",
    "code_review.copied": "Código copiado al portapapeles",
    "code_review.copy_failed": "Error al copiar",
    "chat.new_session": "Nueva sesión",
    "chat.delete": "Eliminar",
    "chat.no_sessions": "Sin sesiones aún",
    "chat.collapse": "Contraer",
    "chat.expand": "Expandir",
    "chat.sources": "Fuentes:",
    "chat.searching": "Buscando en el código del proyecto...",
    "chat.error_loading_session": "Error al cargar sesión",
    "chat.error_creating_session": "Error al crear sesión",
    "chat.error_deleting_session": "Error al eliminar sesión",
    "chat.error_response": "Error al obtener respuesta",
    "chat.history_cleared": "Historial limpiado",
    "chat.error_clearing": "Error al limpiar historial",
    "viewer.editing": "EDITANDO",
    "viewer.save": "Guardar",
    "viewer.saving": "Guardando\u2026",
    "viewer.cancel": "Cancelar",
    "viewer.search": "Buscar",
    "viewer.edit": "Editar",
    "viewer.search_placeholder": "Buscar en el archivo...",
    "viewer.saved": "Archivo guardado",
    "viewer.save_error": "Error al guardar el archivo",

    "docs.title": "Documentación",
    "docs.generate_doc": "Generar Documentación",
    "docs.generating_doc": "Generando Documentación\u2026",
    "docs.generate_readme": "Generar README",
    "docs.generating_readme": "Generando README\u2026",
    "docs.export_pdf": "Exportar PDF",
    "docs.readme_title": "README generado",
    "docs.readme_path": "Ruta:",
    "docs.readme_overwritten": "Archivo existente sobrescrito.",
    "docs.readme_created": "Archivo nuevo creado.",
    "docs.error_generating": "Error al generar documentación",
    "docs.readme_success": "README generado correctamente",
    "docs.readme_error": "Error al generar README",
    "docs.export_first": "Genera documentación primero",
    "docs.allow_popups": "Permite ventanas emergentes para exportar PDF",
    "docs.about.title": "Acerca de DevPilot",
    "docs.about.text": "DevPilot es un asistente de desarrollo IA local. Analiza tu código fuente, lo indexa con búsqueda vectorial (RAG) y te permite chatear con un LLM que entiende tu proyecto. Todo el procesamiento ocurre en tu máquina.",
    "docs.quick_start.title": "Inicio Rápido",
    "docs.quick_start.step1": "Abre una carpeta de proyecto desde la página Proyectos (arrastra o explora).",
    "docs.quick_start.step2": "Espera a que el análisis termine. El índice RAG se construye automáticamente.",
    "docs.quick_start.step3": "Ve a Chat y haz preguntas sobre tu código.",
    "docs.quick_start.step4": "Usa el Explorador de Archivos para ver, editar y buscar archivos.",
    "docs.quick_start.step5": "Configura tu proveedor LLM en Ajustes (Ollama o Groq).",
    "docs.shortcuts.title": "Atajos de Teclado",
    "docs.shortcuts.hint": "Presiona {key} en cualquier lado para ver todos los atajos.",
    "docs.shortcuts.show": "Mostrar atajos de teclado",
    "docs.shortcuts.close": "Cerrar modal / cancelar",
    "docs.shortcuts.file_search": "Buscar archivo (Explorador)",
    "docs.shortcuts.project_search": "Buscar en el código del proyecto",
    "docs.shortcuts.file_find": "Buscar dentro del archivo (Visor)",
    "docs.shortcuts.toggle_edit": "Activar modo edición (Visor)",
    "docs.shortcuts.save_file": "Guardar archivo (Visor)",
    "docs.shortcuts.send": "Enviar mensaje (Chat)",
    "docs.providers.title": "Proveedores LLM",
    "docs.providers.ollama_title": "Ollama (por defecto)",
    "docs.providers.ollama_desc": "Modelos locales vía Ollama. Instala Ollama por separado y descarga un modelo (ej. {cmd}).",
    "docs.providers.groq_title": "Groq (nube)",
    "docs.providers.groq_desc": "Inferencia rápida en la nube vía Groq API. Crea una clave gratuita en {url} y agrégala a tu archivo .env.",
    "docs.rag.title": "RAG (Generación Aumentada por Recuperación)",
    "docs.rag.para1": "DevPilot indexa tu código de proyecto en ChromaDB, una base de datos vectorial local. Cuando haces una pregunta en Chat, recupera los fragmentos de código más relevantes y los incluye como contexto para el LLM, mostrando citas de las fuentes en línea.",
    "docs.rag.para2": "El índice se reconstruye automáticamente cuando abres o subes un proyecto. Guardar un archivo lo reindexa automáticamente.",
    "docs.api.title": "Endpoints de API",
    "docs.api.description": "Todas las rutas de la API tienen el prefijo {prefix}. Documentación Swagger completa en {docs}.",
    "docs.api.health": "Verificación básica de salud",
    "docs.api.health_detailed": "Estado completo del servicio",
    "docs.api.metrics": "Métricas de Prometheus",
    "docs.api.settings": "Configuración LLM/RAG",
    "docs.api.analyze": "Analizar estadísticas del proyecto",
    "docs.api.question_stream": "Q&A del proyecto en streaming",
    "docs.api.tool_stream": "Chat con llamada a herramientas",
    "docs.api.export": "Exportar proyecto como ZIP",
    "docs.api.share": "Generar enlace compartible",
    "docs.api.shared": "Ver proyecto compartido",
  },
};
