import { createContext, useContext, useState, type ReactNode } from "react";

type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const value: LanguageContextType = {
    language,
    setLanguage,
    t: (key: string, params?: Record<string, string | number>) => {
      let text = translations[language]?.[key] ?? translations.en?.[key] ?? key;
      if (params) {
        for (const [k, v] of Object.entries(params)) {
          text = text.replace(`{${k}}`, String(v));
        }
      }
      return text;
    },
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "DevPilot",
    "nav.dashboard": "Dashboard",
    "nav.projects": "Projects",
    "nav.chat": "Chat",
    "nav.documentation": "Documentation",
    "nav.health": "Health",
    "nav.settings": "Settings",
    "navbar.subtitle": "AI Developer Assistant",
    "settings.title": "Settings",
    "settings.language": "Language",
    "settings.language_label": "Select your preferred language",
    "settings.provider": "Provider",
    "settings.provider_label": "Choose which LLM backend to use",
    "settings.ollama_model": "Ollama Model",
    "settings.groq_model": "Groq Model",
    "settings.ollama_url": "Ollama Base URL",
    "settings.generation": "Generation",
    "settings.temperature": "Temperature",
    "settings.max_tokens": "Max Tokens",
    "settings.save": "Save Settings",
    "settings.saved": "Settings saved",
    "settings.save_error": "Failed to save settings",
    "settings.rag": "RAG",
    "settings.rag_desc": "Semantic code chunking for vector search",
    "settings.rag_chunk_lines": "Chunk Lines",
    "settings.rag_overlap": "Overlap Lines",
    "settings.rag_max_chunks": "Max Chunks per File",
    "settings.rag_max_results": "Max Search Results",
    "project.title": "Project",
    "doc.title": "Documentation",
    "dashboard.title": "Dashboard",
    "viewer.title": "File Viewer",
    "viewer.select": "Select a file to view its contents.",
    "viewer.code": "Code",
    "viewer.ai": "AI",
    "viewer.explain": "Explain with AI",
    "viewer.generating": "Generating...",
    "viewer.waiting": "Waiting for response...",
    "viewer.no_explanation": "No explanation generated yet.",
    "viewer.chars": "chars",
    "viewer.error": "Unable to generate explanation.",
    "stats.total_files": "Total Files",
    "stats.lines": "Lines",
    "stats.functions": "Functions",
    "stats.classes": "Classes",
    "stats.files_line": "{files} files, {lines} lines",
    "explorer.title": "Project Explorer",
    "explorer.search": "Search files...",
    "explorer.search_code": "Search code...",
    "explorer.empty": "Analyze a project to display its files.",
    "chat.title": "Project Chat",
    "chat.no_project": "Open a project from the Dashboard first to start asking questions.",
    "chat.asking_about": "Asking about:",
    "chat.placeholder": "Ask about your project...",
    "chat.send": "Send",
    "chat.thinking": "Thinking...",
    "chat.empty": "Ask anything about your project — architecture, dependencies, how to add features, etc.",
    "chat.error": "Error: Unable to get an answer.",
    "chat.clear": "Clear history",
    "project.select": "Select Project",
    "project.analyze": "Analyze",
    "project.analyzing": "Analyzing...",
    "project.browse": "Browse",
    "project.path_placeholder": "Select a project...",
    "project.analyze_title": "Analyze Project",
    "current_project.title": "Current Project",
    "current_project.no_project": "No project selected",
    "current_project.close": "Close Project",
    "recent.title": "Recent Projects",
    "recent.empty": "No projects analyzed yet.",
    "rag.ready": "RAG Active",
    "rag.not_ready": "RAG Unavailable",
    "rag.chunks": "{chunks} chunks indexed",
    "rag.project_chunks": "{chunks} for this project",
    "rag.rebuild": "Rebuild Index",
    "rag.clear": "Clear Index",
    "rag.chunk_lines": "Chunk size: {n} lines",
    "rag.overlap": "Overlap: {n} lines",
    "rag.reindexed": "{files} files reindexed",
    "rag.rebuild_failed": "Rebuild failed",
    "rag.clear_success": "RAG index cleared",
    "rag.clear_failed": "Clear failed",
    "recent.clear": "Clear all",
    "lang.en": "English",
    "lang.es": "Spanish",
    "settings.ai_model": "AI Model",
    "settings.ai_model_desc": "Choose which AI service to use for chat, code review, and documentation.",
    "settings.model_quality": "Model quality",
    "settings.ollama_model_name": "Ollama model name",
    "settings.ollama_model_placeholder": "qwen2.5-coder:7b",
    "settings.advanced": "Advanced settings",
    "settings.temperature_desc": "Lower = more precise. Higher = more creative.",
    "settings.temperature_precise": "0 — Precise",
    "settings.temperature_creative": "2 — Creative",
    "settings.max_tokens_desc": "Maximum response length from the AI.",
    "settings.ollama_url_desc": "Change only if Ollama runs on a different machine.",
    "settings.rag_desc_short": "How code is split and searched for AI context.",
    "settings.api_key": "{provider} API Key",
    "settings.api_key_placeholder": "sk-... ({provider} API key)",
    "settings.test": "Test",
    "settings.connected": "Connected",
    "settings.failed": "Failed",
    "settings.load_error": "Failed to load settings",
    "settings.test_connection_failed": "Connection test failed",
    "settings.switched_to_auto": "Switched to Auto provider",
    "settings.enter_api_key": "Enter an API key for {provider} first",
    "badge.local": "Local",
    "badge.free": "Free",
    "badge.key": "Key",
    "provider.ollama.label": "Ollama",
    "provider.ollama.desc": "Open-source models, runs on your machine",
    "provider.openai.label": "OpenAI",
    "provider.openai.desc": "GPT-4o, GPT-4o-mini. Fast & powerful",
    "provider.anthropic.label": "Claude",
    "provider.anthropic.desc": "Claude 3.5 Sonnet. Great for code review",
    "provider.google.label": "Gemini",
    "provider.google.desc": "Gemini 2.0 Flash. Google's latest",
    "provider.groq.label": "Groq",
    "provider.groq.desc": "Fast inference. Free tier available",
    "provider.auto.label": "Auto",
    "provider.auto.desc": "Smart detection. Ollama → Groq → first available",
    "preset.fast.label": "Fast",
    "preset.fast.desc": "Quick responses",
    "preset.balanced.label": "Balanced",
    "preset.balanced.desc": "Good quality",
    "preset.code.label": "Code",
    "preset.code.desc": "Best for code",
    "project.overview": "Project Overview",
    "project.statistics": "Statistics",
    "project.actions": "Actions",
    "project.rag_index": "RAG Index",
    "project.code_review": "Code Review",
    "project.file_explorer": "File Explorer",
    "project.file_viewer": "File Viewer",
    "project.recent_projects": "Recent Projects",
    "project_actions.summary": "AI Summary",
    "project_actions.generating_summary": "Generating Summary\u2026",
    "project_actions.explain": "Explain Project",
    "project_actions.analyzing": "Analyzing Project\u2026",
    "project_actions.project_summary": "Project Summary",
    "project_actions.project_analysis": "Project Analysis",
    "current_project.previous": "Previous project",
    "current_project.resume": "Resume",
    "current_project.opening": "Opening...",
    "current_project.copy": "Copy",
    "current_project.share": "Share",
    "current_project.export": "Export",
    "current_project.resume_error": "Failed to resume project",
    "current_project.share_error": "Failed to generate share link",
    "current_project.link_copied": "Link copied to clipboard",
    "stats.lang_distribution": "Language Distribution",
    "code_review.run": "AI Code Review",
    "code_review.running": "Running Code Review\u2026",
    "code_review.title": "Code Review",
    "code_review.analyzing": "Analyzing source files\u2026",
    "code_review.categories_reviewed": "{count} categories reviewed",
    "code_review.issues": "issues",
    "code_review.issue_single": "issue",
    "code_review.ai_fix": "AI Fix",
    "code_review.generating_fix": "Generating fix...",
    "code_review.waiting_ai": "Waiting for AI...",
    "code_review.suggested_fix": "Suggested fix",
    "code_review.copy": "Copy",
    "code_review.file": "File:",
    "code_review.line": "Line: ~{line}",
    "code_review.issue_label": "Issue:",
    "code_review.fix_label": "Fix:",
    "code_review.failed_fix": "Failed to fix: {file}",
    "code_review.copied": "Code copied to clipboard",
    "code_review.copy_failed": "Failed to copy",
    "chat.new_session": "New session",
    "chat.delete": "Delete",
    "chat.no_sessions": "No sessions yet",
    "chat.collapse": "Collapse",
    "chat.expand": "Expand",
    "chat.sources": "Sources:",
    "chat.searching": "Searching project code...",
    "chat.error_loading_session": "Error loading session",
    "chat.error_creating_session": "Error creating session",
    "chat.error_deleting_session": "Error deleting session",
    "chat.error_response": "Error al obtener respuesta",
    "chat.history_cleared": "Historial limpiado",
    "chat.error_clearing": "Error al limpiar historial",
    "viewer.editing": "EDITING",
    "viewer.save": "Save",
    "viewer.saving": "Saving\u2026",
    "viewer.cancel": "Cancel",
    "viewer.search": "Search",
    "viewer.edit": "Edit",
    "viewer.search_placeholder": "Search in file...",
    "viewer.saved": "File saved",
    "viewer.save_error": "Error saving file",
  },
  es: {
    "app.name": "DevPilot",
    "nav.dashboard": "Dashboard",
    "nav.projects": "Proyectos",
    "nav.chat": "Chat",
    "nav.documentation": "Documentación",
    "nav.health": "Estado",
    "nav.settings": "Configuración",
    "navbar.subtitle": "Asistente de Desarrollo IA",
    "settings.title": "Configuración",
    "settings.language": "Idioma",
    "settings.language_label": "Selecciona tu idioma preferido",
    "settings.provider": "Proveedor",
    "settings.provider_label": "Elige qué backend LLM usar",
    "settings.ollama_model": "Modelo Ollama",
    "settings.groq_model": "Modelo Groq",
    "settings.ollama_url": "URL Base Ollama",
    "settings.generation": "Generación",
    "settings.temperature": "Temperatura",
    "settings.max_tokens": "Máx. Tokens",
    "settings.save": "Guardar Cambios",
    "settings.saved": "Configuración guardada",
    "settings.save_error": "Error al guardar configuración",
    "settings.rag": "RAG",
    "settings.rag_desc": "Fragmentación semántica de código para búsqueda vectorial",
    "settings.rag_chunk_lines": "Líneas por Fragmento",
    "settings.rag_overlap": "Líneas de Solapamiento",
    "settings.rag_max_chunks": "Máx. Fragmentos por Archivo",
    "settings.rag_max_results": "Máx. Resultados de Búsqueda",
    "project.title": "Proyecto",
    "doc.title": "Documentación",
    "dashboard.title": "Dashboard",
    "viewer.title": "Visor de Archivos",
    "viewer.select": "Selecciona un archivo para ver su contenido.",
    "viewer.code": "Código",
    "viewer.ai": "IA",
    "viewer.explain": "Explicar con IA",
    "viewer.generating": "Generando...",
    "viewer.waiting": "Esperando respuesta...",
    "viewer.no_explanation": "Aún no se generó ninguna explicación.",
    "viewer.chars": "caracteres",
    "viewer.error": "No se pudo generar la explicación.",
    "stats.total_files": "Archivos Totales",
    "stats.lines": "Líneas",
    "stats.functions": "Funciones",
    "stats.classes": "Clases",
    "stats.files_line": "{files} arch., {lines} líneas",
    "explorer.title": "Explorador de Archivos",
    "explorer.search": "Buscar archivos...",
    "explorer.search_code": "Buscar código...",
    "explorer.empty": "Analiza un proyecto para ver sus archivos.",
    "chat.title": "Chat del Proyecto",
    "chat.no_project": "Abre un proyecto desde el Dashboard primero para hacer preguntas.",
    "chat.asking_about": "Preguntando sobre:",
    "chat.placeholder": "Pregunta sobre tu proyecto...",
    "chat.send": "Enviar",
    "chat.thinking": "Pensando...",
    "chat.empty": "Pregunta cualquier cosa sobre tu proyecto — arquitectura, dependencias, cómo añadir funciones, etc.",
    "chat.error": "Error: No se pudo obtener una respuesta.",
    "chat.clear": "Limpiar historial",
    "project.select": "Seleccionar Proyecto",
    "project.analyze": "Analizar",
    "project.analyzing": "Analizando...",
    "project.browse": "Examinar",
    "project.path_placeholder": "Selecciona un proyecto...",
    "project.analyze_title": "Analizar Proyecto",
    "current_project.title": "Proyecto Actual",
    "current_project.no_project": "Ningún proyecto seleccionado",
    "current_project.close": "Cerrar Proyecto",
    "recent.title": "Proyectos Recientes",
    "recent.empty": "Aún no se analizaron proyectos.",
    "rag.ready": "RAG Activo",
    "rag.not_ready": "RAG No Disponible",
    "rag.chunks": "{chunks} fragmentos indexados",
    "rag.project_chunks": "{chunks} para este proyecto",
    "rag.rebuild": "Reconstruir Índice",
    "rag.clear": "Limpiar Índice",
    "rag.chunk_lines": "Tamaño: {n} líneas",
    "rag.overlap": "Solapamiento: {n} líneas",
    "rag.reindexed": "{files} archivos reindexados",
    "rag.rebuild_failed": "Error al reconstruir",
    "rag.clear_success": "Índice RAG limpiado",
    "rag.clear_failed": "Error al limpiar",
    "recent.clear": "Limpiar todo",
    "lang.en": "Inglés",
    "lang.es": "Español",
    "settings.ai_model": "Modelo de IA",
    "settings.ai_model_desc": "Elige qué servicio de IA usar para chat, revisión de código y documentación.",
    "settings.model_quality": "Calidad del modelo",
    "settings.ollama_model_name": "Nombre del modelo Ollama",
    "settings.ollama_model_placeholder": "qwen2.5-coder:7b",
    "settings.advanced": "Opciones avanzadas",
    "settings.temperature_desc": "Menor = más preciso. Mayor = más creativo.",
    "settings.temperature_precise": "0 — Preciso",
    "settings.temperature_creative": "2 — Creativo",
    "settings.max_tokens_desc": "Longitud máxima de respuesta de la IA.",
    "settings.ollama_url_desc": "Cambia solo si Ollama se ejecuta en otra máquina.",
    "settings.rag_desc_short": "Cómo se divide y busca el código para el contexto de IA.",
    "settings.api_key": "Clave API de {provider}",
    "settings.api_key_placeholder": "sk-... (clave API de {provider})",
    "settings.test": "Probar",
    "settings.connected": "Conectado",
    "settings.failed": "Falló",
    "settings.load_error": "Error al cargar configuración",
    "settings.test_connection_failed": "Error de conexión",
    "settings.switched_to_auto": "Cambiado a proveedor Auto",
    "settings.enter_api_key": "Ingresa una clave API para {provider} primero",
    "badge.local": "Local",
    "badge.free": "Gratis",
    "badge.key": "Clave",
    "provider.ollama.label": "Ollama",
    "provider.ollama.desc": "Modelos open-source, se ejecutan en tu máquina",
    "provider.openai.label": "OpenAI",
    "provider.openai.desc": "GPT-4o, GPT-4o-mini. Rápidos y potentes",
    "provider.anthropic.label": "Claude",
    "provider.anthropic.desc": "Claude 3.5 Sonnet. Ideal para revisión de código",
    "provider.google.label": "Gemini",
    "provider.google.desc": "Gemini 2.0 Flash. Lo último de Google",
    "provider.groq.label": "Groq",
    "provider.groq.desc": "Inferencia rápida. Nivel gratuito disponible",
    "provider.auto.label": "Auto",
    "provider.auto.desc": "Detección inteligente. Ollama → Groq → primero disponible",
    "preset.fast.label": "Rápido",
    "preset.fast.desc": "Respuestas rápidas",
    "preset.balanced.label": "Balanceado",
    "preset.balanced.desc": "Buena calidad",
    "preset.code.label": "Código",
    "preset.code.desc": "Ideal para código",
    "project.overview": "Resumen del Proyecto",
    "project.statistics": "Estadísticas",
    "project.actions": "Acciones",
    "project.rag_index": "Índice RAG",
    "project.code_review": "Revisión de Código",
    "project.file_explorer": "Explorador de Archivos",
    "project.file_viewer": "Visor de Archivos",
    "project.recent_projects": "Proyectos Recientes",
    "project_actions.summary": "Resumen IA",
    "project_actions.generating_summary": "Generando Resumen\u2026",
    "project_actions.explain": "Explicar Proyecto",
    "project_actions.analyzing": "Analizando Proyecto\u2026",
    "project_actions.project_summary": "Resumen del Proyecto",
    "project_actions.project_analysis": "Análisis del Proyecto",
    "current_project.previous": "Proyecto anterior",
    "current_project.resume": "Reanudar",
    "current_project.opening": "Abriendo...",
    "current_project.copy": "Copiar",
    "current_project.share": "Compartir",
    "current_project.export": "Exportar",
    "current_project.resume_error": "Error al retomar proyecto",
    "current_project.share_error": "Error al generar link de compartir",
    "current_project.link_copied": "Link copiado al portapapeles",
    "stats.lang_distribution": "Distribución de Lenguajes",
    "code_review.run": "Revisión de Código IA",
    "code_review.running": "Ejecutando Revisión\u2026",
    "code_review.title": "Revisión de Código",
    "code_review.analyzing": "Analizando archivos fuente\u2026",
    "code_review.categories_reviewed": "{count} categorías revisadas",
    "code_review.issues": "problemas",
    "code_review.issue_single": "problema",
    "code_review.ai_fix": "Corrección IA",
    "code_review.generating_fix": "Generando corrección...",
    "code_review.waiting_ai": "Esperando a la IA...",
    "code_review.suggested_fix": "Corrección sugerida",
    "code_review.copy": "Copiar",
    "code_review.file": "Archivo:",
    "code_review.line": "Línea: ~{line}",
    "code_review.issue_label": "Problema:",
    "code_review.fix_label": "Corrección:",
    "code_review.failed_fix": "Error al corregir: {file}",
    "code_review.copied": "Código copiado al portapapeles",
    "code_review.copy_failed": "Error al copiar",
    "chat.new_session": "Nueva sesión",
    "chat.delete": "Eliminar",
    "chat.no_sessions": "Sin sesiones aún",
    "chat.collapse": "Contraer",
    "chat.expand": "Expandir",
    "chat.sources": "Fuentes:",
    "chat.searching": "Buscando en el código del proyecto...",
    "chat.error_loading_session": "Error al cargar sesión",
    "chat.error_creating_session": "Error al crear sesión",
    "chat.error_deleting_session": "Error al eliminar sesión",
    "chat.error_response": "Error al obtener respuesta",
    "chat.history_cleared": "Historial limpiado",
    "chat.error_clearing": "Error al limpiar historial",
    "viewer.editing": "EDITANDO",
    "viewer.save": "Guardar",
    "viewer.saving": "Guardando\u2026",
    "viewer.cancel": "Cancelar",
    "viewer.search": "Buscar",
    "viewer.edit": "Editar",
    "viewer.search_placeholder": "Buscar en el archivo...",
    "viewer.saved": "Archivo guardado",
    "viewer.save_error": "Error al guardar el archivo",
  },
};
